/**
 * Application factory.
 * Responsibility: build a fully wired, not yet listening Fastify instance.
 * Composition order is explicit: logger, plugins, middlewares, routes.
 * Returning the instance without listening is what makes the app testable by injection.
 */
import Fastify, { type FastifyInstance } from 'fastify';
import type { AppConfig } from '../config/index.js';
import { HealthService } from '../modules/health/health.service.js';
import { buildPdfToImagesManifest } from '../modules/pdf-to-images/pdf-to-images.schema.js';
import { PdfToImagesService } from '../modules/pdf-to-images/pdf-to-images.service.js';
import { toolRegistry } from '../modules/registry/registry.service.js';
import { WorkspaceManager } from '../modules/workspace/workspace.manager.js';
import { LocalWorkspaceStorage } from '../modules/workspace/workspace.storage.js';
import { createRedisPlaceholderProbe, type DependencyProbe } from '../platform/dependency.js';
import { registerMiddlewares } from '../middlewares/index.js';
import { registerPlugins } from '../plugins/index.js';
import { registerRoutes } from '../routes/index.js';
import { SERVICE_NAME } from '../shared/constants.js';
import { newRequestId } from '../utils/id.js';
import { buildLoggerOptions } from './logger.js';
import { SERVICE_PHASE, SERVICE_VERSION } from './version.js';

export interface BuiltApp {
  app: FastifyInstance;
  healthService: HealthService;
  workspaces: WorkspaceManager;
}

export interface BuildAppOptions {
  config: AppConfig;
  /** Extra dependency probes, used by tests and by later phases. */
  probes?: readonly DependencyProbe[];
  /** Overrides the configured workspace root, used by tests. */
  workspaceRoot?: string;
}

export async function buildApp(options: BuildAppOptions): Promise<BuiltApp> {
  const { config } = options;

  const app = Fastify({
    logger: buildLoggerOptions(config),
    // Correlation ids are generated by us so they are uuid shaped, not sequential.
    genReqId: () => newRequestId(),
    requestIdHeader: 'x-request-id',
    requestIdLogLabel: 'requestId',
    // The request context middleware owns request logging: one line per response with
    // timing, instead of Fastify's default incoming plus completed pair.
    disableRequestLogging: true,
    bodyLimit: config.server.bodyLimitBytes,
    requestTimeout: config.server.requestTimeoutMs,
    trustProxy: true,
    ignoreTrailingSlash: true,
  });

  const healthService = new HealthService({
    service: SERVICE_NAME,
    version: SERVICE_VERSION,
    env: config.env,
    phase: SERVICE_PHASE,
    probes: options.probes ?? [createRedisPlaceholderProbe()],
  });

  const storage = new LocalWorkspaceStorage(options.workspaceRoot ?? config.workspace.root);
  await storage.ensureRoot();
  const workspaces = new WorkspaceManager({ storage });

  // Manifests are registered once per process, so rebuilding the app in tests is safe.
  const manifest = buildPdfToImagesManifest(config.upload.maxFileBytes);
  if (!toolRegistry.has(manifest.slug)) toolRegistry.register(manifest);

  const pdfToImagesService = new PdfToImagesService({
    registry: toolRegistry,
    workspaces,
    ttlMs: config.workspace.uploadTtlMs,
    logger: app.log,
  });

  await registerPlugins(app, config, SERVICE_VERSION);
  registerMiddlewares(app, {
    apiVersion: SERVICE_VERSION,
    isProduction: config.isProduction,
  });
  await registerRoutes(app, { healthService, pdfToImagesService });

  await app.ready();
  return { app, healthService, workspaces };
}

