/**
 * Download token signer.
 * Responsibility: mint and verify short lived, tamper evident grants that fully describe one
 * downloadable artefact, using an HMAC over a canonical payload.
 *
 * Architecture Notes
 * The grant is stateless on purpose. A server side download table would have to be shared by
 * every worker and every instance, which turns a link into a distributed lookup and gives a
 * crash the power to strand a finished job. Putting the claims inside the token instead makes a
 * download a pure function of the token plus the workspace on disk, so nothing has to be
 * replicated and expiry needs no sweeper of its own. The signature is what keeps that safe: the
 * payload is attacker visible but not attacker writable, so a client cannot rename a workspace,
 * point at another scope, extend its own expiry or claim a larger size. Comparison is timing
 * safe because the signature is checked on every anonymous request, which is exactly the shape
 * of an oracle if it leaked byte positions. Tokens carry a version prefix so the payload can
 * change later without silently accepting an old format.
 */
import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { downloadErrors } from './download.errors.js';
import type { DownloadClaims, DownloadKind } from './download.types.js';
import type { StorageScope } from '../../storage/storage.driver.js';

/** Format marker, so a future payload change cannot be confused with this one. */
const TOKEN_VERSION = 'd1';
/** Ceiling on a token we are willing to parse at all. */
const MAX_TOKEN_LENGTH = 1024;
/** Object keys and file names are generated by us, so a strict shape is enforceable. */
const SAFE_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;
const SAFE_ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;
const ALLOWED_SCOPES: readonly StorageScope[] = Object.freeze(['outputs', 'tmp']);
const ALLOWED_KINDS: readonly DownloadKind[] = Object.freeze(['file', 'archive']);
const ALLOWED_CONTENT_TYPES: readonly string[] = Object.freeze([
  'image/png',
  'image/jpeg',
  'application/zip',
]);

export interface DownloadTokenSignerOptions {
  /** HMAC key. A random per process key is generated when none is configured. */
  readonly secret?: string;
  /** Injected for deterministic expiry tests. */
  readonly now?: () => number;
}

function base64url(value: Buffer): string {
  return value.toString('base64url');
}

export class DownloadTokenSigner {
  private readonly secret: Buffer;
  private readonly now: () => number;

  constructor(options: DownloadTokenSignerOptions = {}) {
    const secret = options.secret?.trim();
    // A generated key is correct for a single instance: it invalidates every outstanding link
    // on restart, which is safer than a predictable default that would forge across deployments.
    this.secret = secret !== undefined && secret.length > 0
      ? Buffer.from(secret, 'utf8')
      : randomBytes(32);
    this.now = options.now ?? Date.now;
  }

  /** Sign one set of claims into an opaque token. */
  public sign(claims: DownloadClaims): string {
    assertClaims(claims);
    const payload = base64url(Buffer.from(JSON.stringify(canonical(claims)), 'utf8'));
    return `${TOKEN_VERSION}.${payload}.${this.signature(payload)}`;
  }

  /** Verify a token and return its claims, or throw a stable download error. */
  public verify(token: string): DownloadClaims {
    if (typeof token !== 'string' || token.length === 0 || token.length > MAX_TOKEN_LENGTH) {
      throw downloadErrors.invalidToken();
    }
    const parts = token.split('.');
    if (parts.length !== 3) throw downloadErrors.invalidToken();
    const [version, payload, signature] = parts as [string, string, string];
    if (version !== TOKEN_VERSION) throw downloadErrors.invalidToken();
    if (!this.matches(payload, signature)) throw downloadErrors.invalidToken();

    let decoded: unknown;
    try {
      decoded = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));
    } catch (error) {
      throw downloadErrors.invalidToken(error);
    }

    const claims = readClaims(decoded);
    if (claims.expiresAtMs <= this.now()) throw downloadErrors.expiredToken();
    return claims;
  }

  private signature(payload: string): string {
    return base64url(createHmac('sha256', this.secret).update(payload).digest());
  }

  private matches(payload: string, candidate: string): boolean {
    const expected = Buffer.from(this.signature(payload), 'utf8');
    const provided = Buffer.from(candidate, 'utf8');
    if (expected.length !== provided.length) return false;
    return timingSafeEqual(expected, provided);
  }
}

/** Field order is fixed so the same claims always produce the same payload. */
function canonical(claims: DownloadClaims): Record<string, unknown> {
  return {
    w: claims.workspaceId,
    s: claims.scope,
    k: claims.key,
    f: claims.filename,
    c: claims.contentType,
    b: claims.sizeBytes,
    d: claims.kind,
    t: claims.toolSlug,
    e: claims.expiresAtMs,
  };
}

function readClaims(value: unknown): DownloadClaims {
  if (typeof value !== 'object' || value === null) throw downloadErrors.invalidToken();
  const raw = value as Record<string, unknown>;
  const claims: DownloadClaims = {
    workspaceId: asString(raw['w']),
    scope: asString(raw['s']) as StorageScope,
    key: asString(raw['k']),
    filename: asString(raw['f']),
    contentType: asString(raw['c']),
    sizeBytes: asNumber(raw['b']),
    kind: asString(raw['d']) as DownloadKind,
    toolSlug: asString(raw['t']),
    expiresAtMs: asNumber(raw['e']),
  };
  assertClaims(claims);
  return Object.freeze(claims);
}

function asString(value: unknown): string {
  if (typeof value !== 'string') throw downloadErrors.invalidToken();
  return value;
}

function asNumber(value: unknown): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw downloadErrors.invalidToken();
  return value;
}

/**
 * Shape rules applied on both sides of the signature.
 * Signing rejects a malformed grant so a bug cannot mint one, and verifying rejects it again so
 * a leaked key cannot turn a token into a path.
 */
function assertClaims(claims: DownloadClaims): void {
  if (!SAFE_ID_PATTERN.test(claims.workspaceId)) throw downloadErrors.invalidToken();
  if (!SAFE_NAME_PATTERN.test(claims.key)) throw downloadErrors.invalidToken();
  if (!SAFE_NAME_PATTERN.test(claims.filename)) throw downloadErrors.invalidToken();
  if (!ALLOWED_SCOPES.includes(claims.scope)) throw downloadErrors.invalidToken();
  if (!ALLOWED_KINDS.includes(claims.kind)) throw downloadErrors.invalidToken();
  if (!ALLOWED_CONTENT_TYPES.includes(claims.contentType)) throw downloadErrors.invalidToken();
  if (!Number.isInteger(claims.sizeBytes) || claims.sizeBytes <= 0) {
    throw downloadErrors.invalidToken();
  }
  if (!Number.isInteger(claims.expiresAtMs) || claims.expiresAtMs <= 0) {
    throw downloadErrors.invalidToken();
  }
  if (!SAFE_NAME_PATTERN.test(claims.toolSlug)) throw downloadErrors.invalidToken();
}
