/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ImageToolsRouteImport } from './routes/image-tools'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageToolsIndexRouteImport } from './routes/image-tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ImageToolsSlugRouteImport } from './routes/image-tools.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsRoute = ImageToolsRouteImport.update({
  id: '/image-tools',
  path: '/image-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsIndexRoute = ImageToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImageToolsRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const ImageToolsSlugRoute = ImageToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ImageToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/image-tools/$slug': typeof ImageToolsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/image-tools/': typeof ImageToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/image-tools/$slug': typeof ImageToolsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/image-tools': typeof ImageToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRouteWithChildren
  '/offline': typeof OfflineRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/image-tools/$slug': typeof ImageToolsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/image-tools/': typeof ImageToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/image-tools'
    | '/offline'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/image-tools/$slug'
    | '/tools/$slug'
    | '/image-tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/offline'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/image-tools/$slug'
    | '/tools/$slug'
    | '/image-tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/image-tools'
    | '/offline'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/image-tools/$slug'
    | '/tools/$slug'
    | '/image-tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ImageToolsRoute: typeof ImageToolsRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools': {
      id: '/image-tools'
      path: '/image-tools'
      fullPath: '/image-tools'
      preLoaderRoute: typeof ImageToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/': {
      id: '/image-tools/'
      path: '/'
      fullPath: '/image-tools/'
      preLoaderRoute: typeof ImageToolsIndexRouteImport
      parentRoute: typeof ImageToolsRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/image-tools/$slug': {
      id: '/image-tools/$slug'
      path: '/$slug'
      fullPath: '/image-tools/$slug'
      preLoaderRoute: typeof ImageToolsSlugRouteImport
      parentRoute: typeof ImageToolsRoute
    }
  }
}

interface ImageToolsRouteChildren {
  ImageToolsSlugRoute: typeof ImageToolsSlugRoute
  ImageToolsIndexRoute: typeof ImageToolsIndexRoute
}

const ImageToolsRouteChildren: ImageToolsRouteChildren = {
  ImageToolsSlugRoute: ImageToolsSlugRoute,
  ImageToolsIndexRoute: ImageToolsIndexRoute,
}

const ImageToolsRouteWithChildren = ImageToolsRoute._addFileChildren(
  ImageToolsRouteChildren,
)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ImageToolsRoute: ImageToolsRouteWithChildren,
  OfflineRoute: OfflineRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
